name: On release publish
on: 
  push:
  release:
    types: [published]

jobs:

  gen_version:
    name: Generate software version
    runs-on: ubuntu-latest

    steps:
    # on release we want to use release.tag_name for the version
    - name: Set tegola version (use release.tag_name)
      if: github.event_name == 'release'
      run: echo ${{ github.event.release.tag_name }} > ${{ github.workspace }}/version.txt

    # when it's not a release build use the commit hash for the version tag
    - name: Set tegola version (use commit hash)
      if: github.event_name == 'push'
      run: echo ${{ github.sha }} | cut -c1-7 > ${{ github.workspace }}/version.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: version
        path: ${{ github.workspace }}/version.txt

  build_linux:
    name: Build for Linux and AWS Lambda
    needs: gen_version
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Set tegola version
      run: echo "VERSION=$(cat version/version.txt)" >> $GITHUB_ENV

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build for Linux
      env:
        # build architecture
        GOOS: linux
      run: |
          cd cmd/tegola
          go build -mod vendor -ldflags "-w -X github.com/go-spatial/tegola/cmd/tegola/cmd.Version=${VERSION}"

    # workaround for archives losing permissions 
    # https://github.com/actions/upload-artifact/issues/38
    - name: Zip archive permissions workaround
      run: |
        cd cmd/tegola
        zip -9 -D tegola.zip tegola

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: tegola_linux_amd64
        path: cmd/tegola/tegola.zip

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: cmd/tegola/tegola.zip
        asset_name: tegola_linux_amd64.zip
        asset_content_type: application/zip

    - name: Build tegola_lambda
      env:
        # build architecture
        GOOS: linux
      run: |
          cd cmd/tegola_lambda
          go build -mod vendor -ldflags "-w -X main.Version=${VERSION}"

    # workaround for archives losing permissions 
    # https://github.com/actions/upload-artifact/issues/38
    - name: Zip archive permissions workaround
      run: |
        cd cmd/tegola_lambda
        zip -9 -D tegola.zip tegola_lambda

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: tegola_lambda
        path: cmd/tegola_lambda/tegola.zip

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: cmd/tegola_lambda/tegola.zip
        asset_name: tegola_lambda.zip
        asset_content_type: application/zip

  build_macos:
    name: Build for MacOS
    needs: gen_version
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Set Tegola version
      run: echo "VERSION=$(cat version/version.txt)" >> $GITHUB_ENV

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build for Darwin
      env:
        GOOS: darwin
      run: |
          cd cmd/tegola
          go build -mod vendor -ldflags "-w -X github.com/go-spatial/tegola/cmd/tegola/cmd.Version=${VERSION}"

    # workaround for archives losing permissions
    # https://github.com/actions/upload-artifact/issues/38
    - name: Zip archive permissions workaround
      run: |
        cd cmd/tegola
        zip -9 -D tegola.zip tegola

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: tegola_darwin_amd64
        path: cmd/tegola/tegola.zip

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: cmd/tegola/tegola.zip
        asset_name: tegola_darwin_amd64.zip
        asset_content_type: application/zip

  build_docker:
    name: Build Docker image and publish to Docker Hub
    needs: gen_version
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_ORG: gospatial
      DOCKERHUB_REPO: tegola

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Set tegola version
      run: echo "VERSION=$(cat version/version.txt)" >> $GITHUB_ENV

    - name: Build and tag Docker container
      run: |
        docker build -t tegola --build-arg VERSION=${VERSION} .
        docker tag tegola:latest ${DOCKERHUB_ORG}/${DOCKERHUB_REPO}:${VERSION}
        docker tag tegola:latest ${DOCKERHUB_ORG}/${DOCKERHUB_REPO}:latest

    - name: Publish Docker container
      if: github.event_name == 'release'
      env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin
        docker push ${DOCKERHUB_ORG}/${DOCKERHUB_REPO}:${VERSION}
        docker push ${DOCKERHUB_ORG}/${DOCKERHUB_REPO}:latest

  build_windows:
    name: Build for Windows
    needs: gen_version
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
#      with:
        # necessary until Go modules have been adopted in this repo
 #       path: go\src\github.com\go-spatial\tegola

    - name: Download version artifact
      uses: actions/download-artifact@v1
      with:
        name: version

    - name: Set tegola version
      run: echo "VERSION=$(cat version/version.txt)" >> $GITHUB_ENV

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Build for Windows
#      env:
        # necessary until Go modules have been adopted in this repo
#        GOPATH: ${{ github.workspace }}\go
      run: |
          cd cmd\tegola
          go build -ldflags "-w -X github.com/go-spatial/tegola/cmd/tegola/cmd.Version=$Env:VERSION"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: tegola_windows_amd64
        path: cmd\tegola\tegola.exe

    - name: Compress release asset
      if: github.event_name == 'release'
      #env:
        # necessary until Go modules have been adopted in this repo
        #GOPATH: ${{ github.workspace }}\go
      run: |
          cd cmd\tegola
          7z a tegola.zip tegola.exe

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: cmd\tegola\tegola.zip
        asset_name: tegola_windows_amd64.zip
        asset_content_type: application/zip

